services:
  - type: web
    name: amamora
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /salud
    autoDeployTrigger: commit
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.7
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
